backend:
  name: git-gateway
  # name: github
  repo: https://github.com/bscs-dev-team/bmw
  #repo: bscs-science-learning/bscs-science-learning
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/assets
public_folder: assets

publish_mode: editorial_workflow
display_url: https://bmw-bscs.netlify.com
logo_url: https://bmw-bscs.netlify.com/static/bscs_logo-4764abf3ed875294200baf166ee88a47.svg #Found in browser sources

collections:
    - name: educator-resource-center
      label: Educator Resource Center
      folder: src/content/educator-resource-center
      create: true
      extension: md
      fields:
          - { name: date, label: Date, widget: date }
          - { name: title, label: Title, widget: string }
          - { name: seoCanonicalUrl, label: SEO Canonical URL, widget: string }
          - { name: seoDescription, label: SEO Description, widget: string }
          - { name: seoLang, label: SEO Language, widget: string, default: "en-us", required: false }
          - { name: type, label: Type, widget: select, options: ['Classroom', 'Professional Learning', 'District Planning', 'Citizen Science'] }
          - { name: template, label: template, widget: select, options: ['Image Left', 'Image Right'] }
          - { name: image, label: Image, widget: image }
          - { name: alt, label: Image Alt Text, widget: string }
          - { name: price, label: Price, widget: number, valueType: float, min: 0.0, max: 1000, required: false }
          - { name: courseId, label: Course ID, widget: number, valueType: int, min: 0, max: 10000, default: 0, required: false }
          - { name: gradeLevel, label: Grade Level, widget: select, multiple: true, options: ['Elementary', 'Middle', 'High', 'Postsecondary'], required: false }
          - { name: discipline, label: Discipline, widget: select, multiple: true, options: ['Life Sciences', 'Physical Sciences', 'Earth Sciences', 'Multidisciplinary Sciences'], required: false }
          - { name: programLength, label: Program Length, widget: select, options: ['Full Year', 'Modules'], required: false }
          - { name: additionalTags, label: Additional Tags, widget: list, required: false }
          - { name: body, label: Body, widget: markdown }
          - { name: page, label: Page, widget: hidden, default: educator-resource-center }

    - name: research-resource-center
      label: Research Resource Center
      folder: src/content/research-resource-center
      create: true
      extension: md
      fields:
          - { name: date, label: Date, widget: date }
          - { name: title, label: Title, widget: string }
          - { name: seoCanonicalUrl, label: SEO Canonical URL, widget: string }
          - { name: seoDescription, label: SEO Description, widget: string }
          - { name: seoLang, label: SEO Language, widget: string, default: "en-us", required: false }
          - { name: template, label: template, widget: select, default: 'Image Left', options: ['Image Left', 'Image Right'] }
          - { name: image, label: Image, widget: image }
          - { name: alt, label: Image Alt Text, widget: string }
          - { name: additionalTags, label: Additional Tags, widget: string, required: false }
          - { name: body, label: Body, widget: markdown }
          - { name: page, label: Page, widget: hidden, default: research-resource-center }

    - name: r&d-programs
      label: R&D Programs
      folder: src/content/rd-programs
      create: true
      extension: md
      fields:
          - { name: date, label: Date, widget: date }
          - { name: title, label: Title, widget: string }
          - { name: areas, label: Areas, widget: select, multiple: true, options: ['Area 1', 'Area 2', 'Area 3', 'Area 4'] }
          - { name: seoCanonicalUrl, label: SEO Canonical URL, widget: string }
          - { name: seoDescription, label: SEO Description, widget: string }
          - { name: seoLang, label: SEO Language, widget: string, default: "en-us", required: false }
          - { name: image, label: Image, widget: image }
          - { name: alt, label: Image Alt Text, widget: string }
          - { name: sidebarUrl, label: Sidebar URL, widget: string, required: false }
          - { name: sidebarButtonText, label: Sidebar Button Text, widget: string, required: false }
          - { name: sidebarText, label: Sidebar Text, widget: string, required: false }
          - { name: sidebarContact, label: Sidebar BSCS Contact, widget: string, required: false }
          - { name: sidebarContactText, label: Sidebar Contact Text, widget: string, required: false }
          - { name: additionalTags, label: Additional Tags, widget: string, required: false }
          - { name: body, label: Body, widget: markdown }
          - { name: page, label: Page, widget: hidden, default: rd-programs }

    - name: leadership
      label: Leadership
      folder: src/content/leadership
      identifier_field: fullName
      create: true
      extension: md
      fields:
        - { name: date, label: Date, widget: date }
        - { name: fullName, label: Full Name, widget: string }
        - { name: seoCanonicalUrl, label: SEO Canonical URL, widget: string }
        - { name: seoDescription, label: SEO Description, widget: string }
        - { name: seoLang, label: SEO Language, widget: string, default: "en-us", required: false }
        - { name: type, label: Type, widget: select, options: ['Management', 'Board Member'] }
        - { name: template, label: template, widget: select, options: ['Image Left', 'Image Right'] }
        - { name: image, label: Image, widget: image }
        - { name: alt, label: Image Alt Text, widget: string }
        - { name: additionalTags, label: Additional Tags (optional), widget: string, required: false }
        - { name: body, label: Body, widget: markdown }
        - { name: page, label: Page, widget: hidden, default: leadership }

    - name: staff
      label: Staff
      folder: src/content/staff
      identifier_field: fullName
      create: true
      extension: md
      fields:
        - { name: date, label: Date, widget: date }
        - { name: fullName, label: Full Name, widget: string }
        - { name: firstName, label: First Name (if Full Name is not just <first> <last>), widget: string, required: false }
        - { name: lastName, label: Last Name (if Full Name is not just <first> <last>), widget: string, required: false }
        - { name: title, label: Title, widget: string }
        - { name: url, label: Profile URL, widget: string, required: false}
        - { name: page, label: Page, widget: hidden, default: staff-directory }

    - name: upcoming-teacher-professional-learning
      label: "Upcoming Programs: Teacher Professional Learning"
      folder: src/content/upcoming/teacher-professional-learning
      create: true
      extension: md
      fields:
        - { name: date, label: Date, widget: date }
        - { name: title, label: Title of Program, widget: string }
        - { name: seoCanonicalUrl, label: SEO Canonical URL, widget: string }
        - { name: seoDescription, label: SEO Description, widget: string }
        - { name: seoLang, label: SEO Language, widget: string, default: "en-us", required: false }
        - { name: sidebarRegisterURL, label: Sidebar Registration Link, widget: string, required: false }
        - { name: sidebarRegisterText, label: Sidebar Registration Text, widget: string, required: false }
        - { name: sidebarRegisterTitle, label: Sidebar Registration Title, widget: string, required: false }
        - { name: sidebarContactText, label: Sidebar Contact Text, widget: string, required: false  }
        - { name: sidebarContact, label: Sidebar Contact Person and Info, widget: list,
          field: { label: Contact, name: contact, widget: string },
          required: false
        }
        - { name: sidebarContactTitle, label: Sidebar Contact Title, widget: string, required: false }
        - { name: sidebarContactText, label: Contact Text, widget: string, required: false  }
        - { name: additionalTags, label: Additional Tags (optional), widget: string, required: false }
        - { name: body, label: Body, widget: markdown }
        - { name: page, label: Page, widget: hidden, default: upcoming-programs-teacher-professional-learning }

    # - name: strategic-initiative
    #   label: Strategic Initiative
    #   folder: src/content/strategic-initiatives
    #   create: true
    #   extension: md
    #   fields:
    #     - { name: slug, label: Website URL Path, widget: string }
    #     - { name: date, label: Date, widget: date }
    #     - { name: title, label: Title, widget: string }
    #     # - { name: type, label: Type, widget: select, options: ['Classroom', 'Professional Learning', 'District Planning', 'Citizen Science'] }
    #     - { name: shortDescription, label: Short Description (optional), widget: string, required: false }
    #     - { name: template, label: template, widget: select, options: ['Image Left', 'Image in content', 'Image Right'] }
    #     - { name: image, label: Image, widget: image }
    #     - { name: alt, label: Image Alt Text, widget: string }
    #     - { name: additionalTags, label: Additional Tags (optional), widget: string, required: false }
    #     - { name: body, label: Body, widget: markdown }
    #     - { name: page, label: Page, widget: hidden, default: strategic-initiatives }
